### ISSUE TITLE
reference dataset in abcCellmap

### ISSUE THREAD

**Issue by FionaMoon** [pzhulab/abcCellmap#1]
Hi,
`abcCellmap`  is really helpfull for hematologist like me (who is not very proficiency in bioinformatics). 
I have some questions about this package.
1. Is there any other build-in reference dataset ? I think `query.exp` is too small to predict cell-type.  Where can I get the full dataset in `ABC website` ?
2. Does `abcCellmap`  has the ability to label `unknow` type which is not appear in reference dataset?
Thank you in advance.
Fiona

**Comment by MengyaoLiu-git** [comment]
1. No other build-in reference dataset in abcCellmap, you can replace the ABC reference by your own reference dataset.
The full ABC dataset is available in http://scrna.sklehabc.com/, you can get the "Gene expression matrix" at Download page.
2. abcCellmap was built based on TransferData from Seurat, thus abcCellmap is not able to label unknow cell type beyond the reference dataset.

**Comment by FionaMoon** [comment]
Thank you !
